<?php

return [
    'show_warnings'   => false,
    'orientation'     => 'portrait',
    'defines'         => [
        'DOMPDF_ENABLE_REMOTE'      => true,  // Permet les images distantes
        'DOMPDF_ENABLE_CSS_FLOAT'   => true,
        'DOMPDF_ENABLE_HTML5PARSER' => true,
        'DOMPDF_FONT_HEIGHT_RATIO'  => 1.1,
        'DOMPDF_DPI'                => 150,
        'DOMPDF_PDF_BACKEND'        => 'CPDF',
        'DOMPDF_UNICODE_ENABLED'    => true,
        'DOMPDF_CHROOT'             => realpath(base_path()),
    ],
    'default_paper_size'        => 'A4',
    'default_paper_orientation' => 'portrait',
    'default_font'              => 'DejaVu Sans',
    'convert_entities'          => true,
    'options'                   => [
        'isPhpEnabled'          => false,
        'isRemoteEnabled'       => true,
        'isJavascriptEnabled'   => false,
        'isHtml5ParserEnabled'  => true,
        'isFontSubsettingEnabled' => true,
        'debugPng'              => false,
        'debugKeepTemp'         => false,
        'debugCss'              => false,
        'debugLayout'           => false,
        'debugLayoutLines'      => true,
        'debugLayoutBlocks'     => true,
        'debugLayoutInline'     => true,
        'debugLayoutPaddingBox' => true,
        'dpi'                   => 150,
        'fontHeightRatio'       => 1.1,
        'isRemoteEnabled'       => true,
        'logOutputFile'         => storage_path('logs/dompdf.log'),
        'tempDir'               => storage_path('app/dompdf/temp'),
        'fontDir'               => storage_path('app/dompdf/fonts'),
        'fontCache'             => storage_path('app/dompdf/cache'),
        'chroot'                => realpath(base_path()),
        'allowedRemoteHosts'    => null,
        'artifactPathValidation'=> true,
    ],
];